### PR TITLE
plugins: rebar3 plugins compatibility

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi leonardo.rossi@studenti.unipr.it

### CODE REVIEW

**Comment by balcruz** [comment]
Hi,  rebar3 support is a nice addition.
Do you agree on a small change (see below)?
In list/0 of src/emqttd_plugins.erl file replace lists:merge/2 by lists:umerge/2 in so to avoid duplications.
So the new line will be
```
...

AppFiles = lists:umerge(projects_rebar3_get_list(PluginsDir), \
                        project_other_get_list(PluginsDir)),
...
```

BR,
Bernardo

**Comment by emqplus** [comment]
Hi @balcruz, I was going to merge this PR in 1.1 release, but postponed for I have no time to test;)

**Comment by hachreak** [comment]
Hi @balcruz 
I think it's fine also with `merge` because it should easily distinguish a rebar3 app from a rebar2 app.
But, It's fine, I think I'll use `umerge`.

@emqplus Yesterday evening I was playing with `rebar3 release`.
Maybe, if all works as expected, I'll simplify a bit the PR.
If you see [there](https://github.com/emqtt/emqttd/pull/528/files#diff-702c996b5594ac57d8f569247c98653aR74), I needed to use a different rebar3 profile: `default` profile where I get the module dependency list and from the `prod` profile the plugin compiled code.
My problem was "avoid to add `emqttd` (and all its deps) on `ERL_LIBS` two times (see [here](https://github.com/emqtt/emqttd/pull/528/files#diff-b173861542426ad71342ff82cbbb5fc8R297)).
Do you know if I can have a dependency list from rebar2 projects? (like `rebar3 deps`).

**Comment by emqplus** [comment]
Hi @hachreak, sorry for the delay. I am considering to consolidate the dependency management.

**Comment by hachreak** [comment]
whats' your plan? :)

**Comment by balcruz** [comment]
@hachreak , @emqplus Thanks!

**Comment by hachreak** [comment]
Hi @emqplus 
did you do some major changes about  dependency management?
I'll publish an plugin example compiled by rebar3 to show how to use it with the help of this patch.

**Comment by emqplus** [comment]
hi @hachreak, @balcruz, I plan to use erlang.mk to manage dependencies in 2.0 release. And I created 'relx' project for emqttd broker: https://github.com/emqtt/emqttd-relx, and improved the plugins' configuration and management. Now we could build the emqttd with plugins:

```
git clone https://github.com/emqtt/emqttd-relx.git && make 
```

Please help review the emqttd-relx project and post comments here if any suggestions:)

**Comment by balcruz** [comment]
Thanks @emqplus, I tried it and looks very nice!. Although I prefer rebar3, erlang.mk is a great option too.

**Comment by hachreak** [comment]
Hi at all,
sorry for the delay.
I published a special branch for [emqttd_plugin_template](https://github.com/hachreak/emqttd_plugin_template/tree/rebar3_compatible) compiled with `rebar3`.
Most of changes are only there to be able to run `emqttd` + the plugin with:
```
docker-compose build
docker-compose up
```
Most of the work is made by the `rebar.config` + emqttd with the patch in this PR.

**Pull request closed without merging**
