### PR TITLE
Initial rebar3 support

### PR DESCRIPTION
**Pull request by joaohf**
Initial pull request to emqttd/emqttd#289
- Every emqttd plugin should provide a plugins.conf in 'priv' directory. It will automatically handled by rebar3 (see rebar.config.script: plugins will be loaded)
- Using rebar3 cross-compile could be used (http://www.rebar3.org/docs/releases#cross-compiling). This is important when a release needs to be done for multiples OS. E.g: 'rebar3 as prod,rhel-6 release tar' will create a release using rhel-6 erts.
- A special script called emqttd_run was created to init the emqttd. E.g.: 'bin/emqttd_run console'.
  I would like to use default relx start_script instead of create one. So the approache taken was to use dynamic configuration (http://www.rebar3.org/docs/releases#dynamic-configuration).  And mnesia dir is set using dynamic configuration.

### CODE REVIEW

**Comment by erylee** [comment]
hi @joaohf, really an awesome PR:) I am preparing a PPT for an open source meeting now, and will check the PR in detail later. Thanks for your great work, @joaohf.

**Comment by hachreak** [comment]
hi @erylee, there are news about rebar3 compatibility? :)

**Comment by erylee** [comment]
@hachreak, yeah:) We plan to replace rebar with erlang.mk in 2.0 release.

**Comment by hachreak** [comment]
why do you want to switch to erlang.mk?
rebar3 became the official building tool for erlang: https://github.com/erlang/rebar3

**Comment by emqplus** [comment]
I think erlang.mk did the thing right. Make is the right tool for make:)

https://medium.com/@jlouis666/why-i-use-erlang-mk-708597c0dd08#.ybt74nvoc

**Comment by hachreak** [comment]
what about if I have my plugin compiled with rebar3?
How can I load it (with all dependencies) with the current version of emqttd?

**Comment by hachreak** [comment]
Hi @emqplus 
I made [some modification](https://github.com/emqtt/emqttd/pull/528) to be able to use emqttd with my plugin compiled with rebar3.
I can confirm it works because I successfully integrated my plugin.
WDYT? There are chances to be merged?

**Comment by emqplus** [comment]
Hi @hachreak, Thanks. I will merge the PR in 1.1 release.

**Comment by hachreak** [comment]
@emqplus thanks for the good news! :D 
When you'll be ready, call me and I'll rebase my PR on top of master. :)

**Comment by emqplus** [comment]
@hachreak, 1.1 release will be ready next week:) I will merge the PR to emq10 branch first.

**Comment by joaohf** [comment]
Two rebar3 features that I like soo much:

http://www.rebar3.org/docs/profiles
http://www.rebar3.org/docs/releases#cross-compiling

**Comment by hzamani** [comment]
Any update here?

**Comment by hachreak** [comment]
There is still pending my PR to be able to write plugins compile by rebar3: https://github.com/emqtt/emqttd/pull/528 (I will publish an example soon)
But I don't know exactly the @emqplus plans about move to erlang.mk.
He wrote `I am considering to consolidate the dependency management`.

**Pull request closed without merging**
